language:
  - swift
osx_image: xcode10.2
# xcode_project: "OpenCore Configurator.xcodeproj"
# xcode_scheme: "OpenCore Configurator"
script:
  - set -o pipefail && xcodebuild -project OpenCore\ Configurator.xcodeproj -scheme OpenCore\ Configurator build archive | xcpretty
