language:
  - swift
osx_image: xcode10.2
# xcode_project: "OpenCore Configurator.xcodeproj"
# xcode_scheme: "OpenCore Configurator"
script:
  - wget https://github.com/acidanthera/MacInfoPkg/releases/download/2.0.5/macserial-2.0.5-mac.zip
  - unzip macserial-2.0.5-mac.zip
  - rm macserial-2.0.5-mac.zip
  - set -o pipefail && xcodebuild -project OpenCore\ Configurator.xcodeproj -scheme OpenCore\ Configurator build | xcpretty
  - ls -lsall ~/Library/Developer/Xcode/DerivedData
  - ls -lsall ~/Library/Developer/Xcode/DerivedData/"OpenCore Configurator"/Build/Products
